name: build-docker.yml
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'xiaoxuan6/codex-management'
    steps:
      - uses: actions/checkout@v1
      - name: Build and publish image
        uses: xiaoxuan6/docker-build-action@develop
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extract-git-tag: true
          image-platform: linux/arm64,linux/amd64
